version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /root/vente
        target: /usr/share/nginx/html
    restart: unless-stopped

      
