version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vente:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt  # Monter les certificats
    restart: unless-stopped
